ARG  VERSION=latest
FROM mcr.microsoft.com/devcontainers/java:21-bullseye

ARG USERNAME=vscode

#### hystory
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R $USERNAME /commandhistory \
    && echo "$SNIPPET" >> "/home/$USERNAME/.bashrc"

USER $USERNAME
